services:
  www:
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=proyecto
    ports:
      - 3306:3306
    volumes:
      - sql_data:/var/lib/mysql
      
volumes:
  sql_data:
